#mysql和阿里druid配置
spring:
    #  application:
    #    name:     #指定应用的名称建议使用小写
    jmx:
        default-domain: qinye-admin
    main:
        allow-bean-definition-overriding: true
    activiti:
        #当遇到同样名字的时候，是否允许覆盖注册
        check-process-definitions: false
    #pagehelper分页插件
    pagehelper:
        helperDialect: mysql
        reasonable: true
        supportMethodsArguments: true
        params: count=countSql
        returnPageInfo: check
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #    url: jdbc:oracle:thin:@192.168.1.98:1521:orcl
        # 本地环境
        #    url: jdbc:mysql://localhost:3306/cereshop1.6?useUnicode=true&allowMultiQueries=true&serverTimezone=UTC
        #    username: root
        #    password: 123456
        # 测试环境
        url: jdbc:mysql://localhost:3306/qy?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
        username: root
        password: 115010.Wang
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            #    driver-class-name: oracle.jdbc.driver.OracleDriver
            # 下面为连接池的补充设置，应用到上面所有数据源中
            # 初始化大小，最小，最大
            initialSize: 1
            minIdle: 3
            maxActive: 200
            # 配置获取连接等待超时的时间
            maxWait: 10000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 300000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 3600000
            #validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall,slf4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            # 合并多个DruidDataSource的监控数据
            useGlobalDataSourceStat: true
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        database: 0
        timeout: 10000
        jedis:
            pool:
                max-active: 6000
                max-wait: 1000
                max-idle: 400
                min-idle: 0
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
